In [145]:
import pandas as pd
from sklearn.svm import SVC,SVR
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score,mean_absolute_error, mean_squared_error, r2_score

In [146]:
import pandas as pd

df = pd.read_excel(r"C:\Users\ASUS\Downloads\bankloan.csv")
df.head()

,ID,Age,Experience,Income,ZIP.Code,Family,CCAvg,Education,Mortgage,Personal.Loan,Securities.Account,CD.Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,0,1


In [147]:
df = df.drop(['ID', 'ZIP.Code'], axis=1)
df

,Age,Experience,Income,Family,CCAvg,Education,Mortgage,Personal.Loan,Securities.Account,CD.Account,Online,CreditCard
0,25,1,49,4,1.6,1,0,0,1,0,0,0
1,45,19,34,3,1.5,1,0,0,1,0,0,0
2,39,15,11,1,1.0,1,0,0,0,0,0,0
3,35,9,100,1,2.7,2,0,0,0,0,0,0
4,35,8,45,4,1.0,2,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
4995,29,3,40,1,1.9,3,0,0,0,0,1,0
4996,30,4,15,4,0.4,1,85,0,0,0,1,0
4997,63,39,24,2,0.3,3,0,0,0,0,0,0
4998,65,40,49,3,0.5,2,0,0,0,0,1,0


In [148]:

#keep personal loan as y
X=df.drop("Personal.Loan",axis=1)
y=df["Personal.Loan"]
y


0       0
1       0
2       0
3       0
4       0
       ..
4995    0
4996    0
4997    0
4998    0
4999    0
Name: Personal.Loan, Length: 5000, dtype: int64

In [149]:
#split dataset into x and y
Xtrain,Xtest,ytrain,ytest=train_test_split(X,y,test_size=0.3,random_state=42)

In [150]:
model=SVC(kernel='linear')

In [151]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(Xtrain, ytrain)

,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive. The penaltyis a squared l2 penalty. For an intuitive visualization of the effectsof scaling the regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"kernel kernel: {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable, default='rbf'Specifies the kernel type to be used in the algorithm. Ifnone is given, 'rbf' will be used. If a callable is given it is used topre-compute the kernel matrix from data matrices; that matrix should bean array of shape ``(n_samples, n_samples)``. For an intuitivevisualization of different kernel types see:ref:`sphx_glr_auto_examples_svm_plot_svm_kernels.py`.",'rbf'
,"degree degree: int, default=3Degree of the polynomial kernel function ('poly').Must be non-negative. Ignored by all other kernels.",3
,"gamma gamma: {'scale', 'auto'} or float, default='scale'Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.- if ``gamma='scale'`` (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,- if 'auto', uses 1 / n_features- if float, must be non-negative... versionchanged:: 0.22 The default value of ``gamma`` changed from 'auto' to 'scale'.",'scale'
,"coef0 coef0: float, default=0.0Independent term in kernel function.It is only significant in 'poly' and 'sigmoid'.",0.0
,"shrinking shrinking: bool, default=TrueWhether to use the shrinking heuristic.See the :ref:`User Guide <shrinking_svm>`.",True
,"probability probability: bool, default=FalseWhether to enable probability estimates. This must be enabled priorto calling `fit`, will slow down that method as it internally uses5-fold cross-validation, and `predict_proba` may be inconsistent with`predict`. Read more in the :ref:`User Guide <scores_probabilities>`...deprecated:: 1.9 The `probability` parameter is deprecated and will be removed in 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`.",'deprecated'
,"tol tol: float, default=1e-3Tolerance for stopping criterion.",0.001
,"cache_size cache_size: float, default=200Specify the size of the kernel cache (in MB).",200
,"class_weight class_weight: dict or 'balanced', default=NoneSet the parameter C of class i to class_weight[i]*C forSVC. If not given, all classes are supposed to haveweight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.",None
,"verbose verbose: bool, default=FalseEnable verbose output. Note that this setting takes advantage of aper-process runtime setting in libsvm that, if enabled, may not workproperly in a multithreaded context.",False


In [152]:
ypredc=svc.predict(Xtest)
ypredc

array([0, 0, 0, ..., 0, 0, 0], shape=(1500,))

In [153]:
con_matrix=confusion_matrix(ytest,ypredc)
con_matrix

array([[1336,    7],
       [ 144,   13]])

In [154]:
print("Training Efficiency :",svc.score(Xtrain,ytrain))
print("Training Efficiency :",svc.score(Xtest,ytest))

Training Efficiency : 0.914
Training Efficiency : 0.8993333333333333


In [155]:
print("Accuracy: ",accuracy_score(ytest,ypredc))
print("Precision",precision_score(ytest,ypredc))
print("Recall",recall_score(ytest,ypredc))
print("F1",f1_score(ytest,ypredc))

Accuracy:  0.8993333333333333
Precision 0.65
Recall 0.08280254777070063
F1 0.14689265536723164


In [156]:
# print("MAE :", mean_absolute_error(ytest, ypredc))
# print("R2 Score :", r2_score(ytest, ypredc))

In [ ]:
                #Taxi trip pricing for regression if cleaning is required then 
df=pd.read_csv(r"C:\Users\ASUS\Downloads\taxi_trip_pricing (1).csv")
df.head()

,Trip_Distance_km,Time_of_Day,Day_of_Week,Passenger_Count,Traffic_Conditions,Weather,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,Weekday,3.0,Low,Clear,3.56,0.80,0.32,53.82,36.2624
1,47.59,Afternoon,Weekday,1.0,High,Clear,NaN,0.62,0.43,40.57,NaN
2,36.87,Evening,Weekend,1.0,High,Clear,2.70,1.21,0.15,37.27,52.9032
3,30.33,Evening,Weekday,4.0,Low,NaN,3.48,0.51,0.15,116.81,36.4698
4,NaN,Evening,Weekday,3.0,High,Clear,2.93,0.63,0.32,22.64,15.6180


In [158]:
df = df.dropna()
df=df.drop(['Weather', 'Passenger_Count', 'Traffic_Conditions','Day_of_Week'], axis=1)
df

,Trip_Distance_km,Time_of_Day,Base_Fare,Per_Km_Rate,Per_Minute_Rate,Trip_Duration_Minutes,Trip_Price
0,19.35,Morning,3.56,0.80,0.32,53.82,36.2624
2,36.87,Evening,2.70,1.21,0.15,37.27,52.9032
5,8.64,Afternoon,2.55,1.71,0.48,89.33,60.2028
12,41.79,Night,4.60,1.77,0.11,86.95,88.1328
14,9.91,Evening,2.32,1.26,0.34,41.72,28.9914
...,...,...,...,...,...,...,...
990,40.17,Evening,3.81,0.66,0.42,62.66,56.6394
992,14.34,Afternoon,3.23,1.01,0.29,45.07,30.7837
994,18.69,Evening,4.90,1.79,0.17,79.41,51.8548
995,5.49,Afternoon,2.39,0.62,0.49,58.39,34.4049


In [159]:
X = df.drop('Trip_Price',axis=1)
y = df['Trip_Price']

In [ ]:
X=pd.get_dummies(df,dtype=int,drop_first=True)
X.head()

<bound method NDFrame.head of      Trip_Distance_km  Base_Fare  Per_Km_Rate  Per_Minute_Rate  \
0               19.35       3.56         0.80             0.32   
2               36.87       2.70         1.21             0.15   
5                8.64       2.55         1.71             0.48   
12              41.79       4.60         1.77             0.11   
14               9.91       2.32         1.26             0.34   
..                ...        ...          ...              ...   
990             40.17       3.81         0.66             0.42   
992             14.34       3.23         1.01             0.29   
994             18.69       4.90         1.79             0.17   
995              5.49       2.39         0.62             0.49   
998             47.56       2.67         0.82             0.17   

     Trip_Duration_Minutes  Trip_Price  Time_of_Day_Evening  \
0                    53.82     36.2624                    0   
2                    37.27     52.9032             

In [161]:
#split dataset into x and y
from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [162]:
model=SVR(kernel='linear',C=10,epsilon=0.01)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

Xtrain = scaler.fit_transform(Xtrain)
Xtest = scaler.transform(Xtest)

In [ ]:
from sklearn.svm import SVR
model.fit(Xtrain, ytrain)

,"kernel kernel: {'linear', 'poly', 'rbf', 'sigmoid', 'precomputed'} or callable, default='rbf'Specifies the kernel type to be used in the algorithm.If none is given, 'rbf' will be used. If a callable is given it isused to precompute the kernel matrix.For an intuitive visualization of different kernel typessee :ref:`sphx_glr_auto_examples_svm_plot_svm_regression.py`",'rbf'
,"degree degree: int, default=3Degree of the polynomial kernel function ('poly').Must be non-negative. Ignored by all other kernels.",3
,"gamma gamma: {'scale', 'auto'} or float, default='scale'Kernel coefficient for 'rbf', 'poly' and 'sigmoid'.- if ``gamma='scale'`` (default) is passed then it uses 1 / (n_features * X.var()) as value of gamma,- if 'auto', uses 1 / n_features- if float, must be non-negative... versionchanged:: 0.22 The default value of ``gamma`` changed from 'auto' to 'scale'.",'scale'
,"coef0 coef0: float, default=0.0Independent term in kernel function.It is only significant in 'poly' and 'sigmoid'.",0.0
,"tol tol: float, default=1e-3Tolerance for stopping criterion.",0.001
,"C C: float, default=1.0Regularization parameter. The strength of the regularization isinversely proportional to C. Must be strictly positive.The penalty is a squared l2. For an intuitive visualization of theeffects of scaling the regularization parameter C, see:ref:`sphx_glr_auto_examples_svm_plot_svm_scale_c.py`.",1.0
,"epsilon epsilon: float, default=0.1Epsilon in the epsilon-SVR model. It specifies the epsilon-tubewithin which no penalty is associated in the training loss functionwith points predicted within a distance epsilon from the actualvalue. Must be non-negative.",0.1
,"shrinking shrinking: bool, default=TrueWhether to use the shrinking heuristic.See the :ref:`User Guide <shrinking_svm>`.",True
,"cache_size cache_size: float, default=200Specify the size of the kernel cache (in MB).",200
,"verbose verbose: bool, default=FalseEnable verbose output. Note that this setting takes advantage of aper-process runtime setting in libsvm that, if enabled, may not workproperly in a multithreaded context.",False
,"max_iter max_iter: int, default=-1Hard limit on iterations within solver, or -1 for no limit.",-1


In [ ]:
ypred=model.predict(Xtest)
ypred

array([38.19071398, 72.60417769, 46.77062761, 52.03478694, 49.2847656 ,
       22.22328497, 64.22881378, 34.3557126 , 54.49572927, 53.58432865,
       40.78109254, 55.71811234, 54.2527128 , 56.81058112, 40.54007115,
       70.52620783, 63.22470577, 57.69521618, 43.22372632, 47.03401836,
       28.97748833, 48.00165466, 71.73842698, 37.52742304, 51.98172885,
       57.34803391, 57.41755739, 49.01645846, 33.08949587, 65.21620897,
       39.61447705, 42.17251209, 63.5533675 , 42.781654  , 56.54811737,
       69.15969194, 79.85508881, 52.65939775, 55.24895095, 25.02788133,
       53.41684087, 70.66442396, 66.46380514, 60.97209853, 35.03092712,
       67.14698559, 48.74835399, 52.11919334, 48.33736313, 40.87015201,
       67.45499601, 59.44455922, 28.89546143, 21.45931815, 52.75897558,
       66.46402404, 54.75069448, 29.84292348, 46.45938347, 59.99354392,
       59.97431973, 49.35800168, 42.27172116, 34.70319504, 78.5511658 ,
       44.60020813, 55.68527755, 39.55886367, 43.72878256, 33.24

In [ ]:
print("Training Efficiency :",model.score(Xtrain,ytrain))
print("Training Efficiency :",model.score(Xtest,ytest))

Training Efficiency : 0.25694490003270076
Training Efficiency : 0.15911889354813902


In [ ]:
print("mae: ",mean_absolute_error(ytest,ypred))
print("R2 Score :", r2_score(ytest, ypred))

mae:  15.845227813621658
R2 Score : 0.15911889354813902
